services:
  backend:
    build: .
    container_name: my_backend
    expose:
      - "8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx:1.31.3-alpine
    container_name: my_nginx
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
  
