"""add_7

Revision ID: 1f2451bd6efd
Revises: 45ca4a2fe524
Create Date: 2026-02-21 14:12:37.961897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2451bd6efd'
down_revision: Union[str, Sequence[str], None] = '45ca4a2fe524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_branches', sa.Column('contractor_company', sa.String(), nullable=True))
    op.add_column('contractor_branches', sa.Column('contractor_inn', sa.String(), nullable=True))
    op.drop_column('contractors', 'contractor_company')
    op.drop_column('contractors', 'contractor_inn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('contractor_inn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('contractor_company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contractor_branches', 'contractor_inn')
    op.drop_column('contractor_branches', 'contractor_company')
    # ### end Alembic commands ###
