"""5

Revision ID: 20260624190632
Revises: 20260617122415
Create Date: 2026-06-24 19:06:33.407077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260624190632'
down_revision: Union[str, Sequence[str], None] = '20260617122415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_reset_tokens_id'), 'reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_reset_tokens_user_id'), 'reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_user_id'), table_name='reset_tokens')
    op.drop_index(op.f('ix_reset_tokens_id'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    # ### end Alembic commands ###
