"""3

Revision ID: 20260305173540
Revises: 20260228151312
Create Date: 2026-03-05 17:35:45.759558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260305173540'
down_revision: Union[str, Sequence[str], None] = '20260228151312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branches_inn_key'), 'branches', type_='unique')
    op.create_index(op.f('ix_branches_inn'), 'branches', ['inn'], unique=True)
    op.create_index(op.f('ix_branches_is_archived'), 'branches', ['is_archived'], unique=False)
    op.create_index(op.f('ix_clients_is_archived'), 'clients', ['is_archived'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.drop_constraint(op.f('companies_inn_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    op.create_index(op.f('ix_companies_is_archived'), 'companies', ['is_archived'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_is_archived'), 'contractor_contracts', ['is_archived'], unique=False)
    op.create_unique_constraint(None, 'contractor_contracts', ['contractor_inn'])
    op.drop_constraint(op.f('contractors_name_key'), 'contractors', type_='unique')
    op.create_index(op.f('ix_contractors_is_archived'), 'contractors', ['is_archived'], unique=False)
    op.create_index(op.f('ix_contractors_name'), 'contractors', ['name'], unique=True)
    op.create_index(op.f('ix_contracts_is_archived'), 'contracts', ['is_archived'], unique=False)
    op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('stage_templates_name_key'), 'stage_templates', type_='unique')
    op.create_index(op.f('ix_stage_templates_is_archived'), 'stage_templates', ['is_archived'], unique=False)
    op.create_index(op.f('ix_stage_templates_name'), 'stage_templates', ['name'], unique=True)
    op.create_index(op.f('ix_stages_is_archived'), 'stages', ['is_archived'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_stages_is_archived'), table_name='stages')
    op.drop_index(op.f('ix_stage_templates_name'), table_name='stage_templates')
    op.drop_index(op.f('ix_stage_templates_is_archived'), table_name='stage_templates')
    op.create_unique_constraint(op.f('stage_templates_name_key'), 'stage_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_contracts_is_archived'), table_name='contracts')
    op.drop_index(op.f('ix_contractors_name'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_is_archived'), table_name='contractors')
    op.create_unique_constraint(op.f('contractors_name_key'), 'contractors', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'contractor_contracts', type_='unique')
    op.drop_index(op.f('ix_contractor_contracts_is_archived'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_companies_is_archived'), table_name='companies')
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.create_unique_constraint(op.f('companies_inn_key'), 'companies', ['inn'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_is_archived'), table_name='clients')
    op.drop_index(op.f('ix_branches_is_archived'), table_name='branches')
    op.drop_index(op.f('ix_branches_inn'), table_name='branches')
    op.create_unique_constraint(op.f('branches_inn_key'), 'branches', ['inn'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
