"""2

Revision ID: 20260615164032
Revises: 5fe28ce6147a
Create Date: 2026-06-15 16:40:34.067136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260615164032'
down_revision: Union[str, Sequence[str], None] = '5fe28ce6147a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_template_id_key'), 'files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('files_template_id_key'), 'files', ['template_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
