"""email_logs

Revision ID: 20260409191835
Revises: 20260403135328
Create Date: 2026-04-09 19:18:38.816431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260409191835'
down_revision: Union[str, Sequence[str], None] = '20260403135328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('status', sa.Enum('PENDING', 'FAILED', 'SENT', name='log_status_enum'), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('to', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('cc', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bcc', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('files_data', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_content', sa.String(length=500), nullable=True),
    sa.Column('body_content', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_creator_id'), 'email_templates', ['creator_id'], unique=False)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_creator_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
