"""15

Revision ID: 20260730130417
Revises: 20260730130332
Create Date: 2026-07-30 13:04:17.697420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260730130417'
down_revision: Union[str, Sequence[str], None] = '20260730130332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('contracts', 'number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('contracts', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
