"""3

Revision ID: 20260616181906
Revises: 20260615164032
Create Date: 2026-06-16 18:19:07.542230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260616181906'
down_revision: Union[str, Sequence[str], None] = '20260615164032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('stamp_file_id', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('stamp_is_public', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'branches', 'files', ['stamp_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'stamp_is_public')
    op.drop_column('branches', 'stamp_file_id')
    # ### end Alembic commands ###
