"""8

Revision ID: 20260714195014
Revises: 20260714124344
Create Date: 2026-07-14 19:50:15.525767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260714195014'
down_revision: Union[str, Sequence[str], None] = '20260714124344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
