"""4

Revision ID: 20260306124001
Revises: 20260305173540
Create Date: 2026-03-06 12:40:04.118272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260306124001'
down_revision: Union[str, Sequence[str], None] = '20260305173540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contractor_contracts_branch_id'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_contractor_contracts_contractor_id'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_contractor_contracts_id'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_contractor_contracts_is_archived'), table_name='contractor_contracts')
    op.drop_table('contractor_contracts')
    op.add_column('contractors', sa.Column('contractor_companies', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'contractor_companies')
    op.create_table('contractor_contracts',
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contractor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contractor_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contractor_inn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('contractor_contracts_branch_id_fkey')),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('contractor_contracts_contractor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contractor_contracts_pkey')),
    sa.UniqueConstraint('contractor_inn', name=op.f('contractor_contracts_contractor_inn_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_contractor_contracts_is_archived'), 'contractor_contracts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_id'), 'contractor_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_contractor_id'), 'contractor_contracts', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_branch_id'), 'contractor_contracts', ['branch_id'], unique=False)
    # ### end Alembic commands ###
