"""11

Revision ID: 20260722130342
Revises: 20260720155043
Create Date: 2026-07-22 13:03:43.829145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260722130342'
down_revision: Union[str, Sequence[str], None] = '20260720155043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branches_stamp_file_id_fkey'), 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'files', ['stamp_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key(op.f('branches_stamp_file_id_fkey'), 'branches', 'files', ['stamp_file_id'], ['id'])
    # ### end Alembic commands ###
