"""9

Revision ID: 20260720150536
Revises: 20260714195014
Create Date: 2026-07-20 15:05:38.284394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260720150536'
down_revision: Union[str, Sequence[str], None] = '20260714195014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('kpp', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('ogrn', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('okpo', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('okved', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('okfs', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('okopf', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('okato', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('legal_adress', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('adress', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('telephone', sa.String(length=40), nullable=True))
    op.add_column('branches', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('director_full_name', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('director_short_name', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('director_position', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('authority_document', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('bik', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('checking_account', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('correspondent_account', sa.String(length=255), nullable=True))
    op.drop_column('branches', 'stamp_is_public')
    op.add_column('companies', sa.Column('kpp', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('ogrn', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('okpo', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('okved', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('okfs', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('okopf', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('okato', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('legal_adress', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('adress', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('telephone', sa.String(length=40), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('director_full_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('director_short_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('director_position', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('authority_document', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('bik', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('checking_account', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('correspondent_account', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'correspondent_account')
    op.drop_column('companies', 'checking_account')
    op.drop_column('companies', 'bik')
    op.drop_column('companies', 'bank_name')
    op.drop_column('companies', 'authority_document')
    op.drop_column('companies', 'director_position')
    op.drop_column('companies', 'director_short_name')
    op.drop_column('companies', 'director_full_name')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'telephone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'adress')
    op.drop_column('companies', 'legal_adress')
    op.drop_column('companies', 'okato')
    op.drop_column('companies', 'okopf')
    op.drop_column('companies', 'okfs')
    op.drop_column('companies', 'okved')
    op.drop_column('companies', 'okpo')
    op.drop_column('companies', 'ogrn')
    op.drop_column('companies', 'kpp')
    op.add_column('branches', sa.Column('stamp_is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('branches', 'correspondent_account')
    op.drop_column('branches', 'checking_account')
    op.drop_column('branches', 'bik')
    op.drop_column('branches', 'bank_name')
    op.drop_column('branches', 'authority_document')
    op.drop_column('branches', 'director_position')
    op.drop_column('branches', 'director_short_name')
    op.drop_column('branches', 'director_full_name')
    op.drop_column('branches', 'website')
    op.drop_column('branches', 'telephone')
    op.drop_column('branches', 'email')
    op.drop_column('branches', 'adress')
    op.drop_column('branches', 'legal_adress')
    op.drop_column('branches', 'okato')
    op.drop_column('branches', 'okopf')
    op.drop_column('branches', 'okfs')
    op.drop_column('branches', 'okved')
    op.drop_column('branches', 'okpo')
    op.drop_column('branches', 'ogrn')
    op.drop_column('branches', 'kpp')
    # ### end Alembic commands ###
