"""10

Revision ID: 20260720155043
Revises: 20260720150536
Create Date: 2026-07-20 15:50:44.604469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260720155043'
down_revision: Union[str, Sequence[str], None] = '20260720150536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('legal_address', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('address', sa.String(length=255), nullable=True))
    op.drop_column('branches', 'adress')
    op.drop_column('branches', 'legal_adress')
    op.add_column('companies', sa.Column('legal_address', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address', sa.String(length=255), nullable=True))
    op.drop_column('companies', 'adress')
    op.drop_column('companies', 'legal_adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('legal_adress', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('adress', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'legal_address')
    op.add_column('branches', sa.Column('legal_adress', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('adress', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('branches', 'address')
    op.drop_column('branches', 'legal_address')
    # ### end Alembic commands ###
