"""8

Revision ID: 20260714124344
Revises: 20260625145219
Create Date: 2026-07-14 12:43:46.102945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260714124344'
down_revision: Union[str, Sequence[str], None] = '20260625145219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_done', sa.Boolean(), nullable=False))
    op.add_column('email_templates', sa.Column('email_content', sa.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'email_content')
    op.drop_column('assignments', 'is_done')
    # ### end Alembic commands ###
