"""7

Revision ID: 20260525140020
Revises: 20260409191835
Create Date: 2026-05-25 14:00:22.396988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260525140020'
down_revision: Union[str, Sequence[str], None] = '20260409191835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('variables', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('required_entities', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_creator_id'), 'document_templates', ['creator_id'], unique=False)
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_index(op.f('ix_document_templates_name'), 'document_templates', ['name'], unique=True)
    op.create_table('generated_documents',
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_generated_documents_creator_id'), 'generated_documents', ['creator_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_id'), 'generated_documents', ['id'], unique=False)
    op.create_index(op.f('ix_generated_documents_template_id'), 'generated_documents', ['template_id'], unique=False)
    op.add_column('files', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'files', ['template_id'])
    op.create_foreign_key(None, 'files', 'document_templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'template_id')
    op.drop_index(op.f('ix_generated_documents_template_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_creator_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_document_templates_name'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_creator_id'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
