"""16

Revision ID: 20260731003948
Revises: 20260730130417
Create Date: 2026-07-31 00:39:49.772031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260731003948'
down_revision: Union[str, Sequence[str], None] = '20260730130417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.alter_column('assignments', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('assignments', 'deadline')
    # ### end Alembic commands ###
