"""13

Revision ID: 20260724110534
Revises: 20260722180852
Create Date: 2026-07-24 11:05:35.513335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260724110534'
down_revision: Union[str, Sequence[str], None] = '20260722180852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('from_emails', sa.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('email_templates', 'email_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('email_content', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.drop_column('email_templates', 'from_emails')
    # ### end Alembic commands ###
