"""add_1

Revision ID: 2dc9db0ff3a7
Revises: 02b41a88173b
Create Date: 2026-02-18 11:30:14.033951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc9db0ff3a7'
down_revision: Union[str, Sequence[str], None] = '02b41a88173b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'inn',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.drop_column('branches', 'main_branch')
    op.add_column('contractors', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_contractors_branch_id'), 'contractors', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'contractors', 'branches', ['branch_id'], ['id'])
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'branches', ['company_id'], ['id'])
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.drop_column('users', 'branch_id')
    op.drop_constraint(None, 'contractors', type_='foreignkey')
    op.drop_index(op.f('ix_contractors_branch_id'), table_name='contractors')
    op.drop_column('contractors', 'branch_id')
    op.add_column('branches', sa.Column('main_branch', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('branches', 'inn',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
