"""add_3

Revision ID: 7978949efa9a
Revises: b6d664cc3ac6
Create Date: 2026-02-18 19:28:11.133066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7978949efa9a'
down_revision: Union[str, Sequence[str], None] = 'b6d664cc3ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contractors', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contractors', type_='unique')
    # ### end Alembic commands ###
