"""missing_1

Revision ID: b2683d4e8e57
Revises: c917542b1757
Create Date: 2026-02-14 13:55:34.775408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2683d4e8e57'
down_revision: Union[str, Sequence[str], None] = 'c917542b1757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('inn', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('telephone', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_manager_id'), 'clients', ['manager_id'], unique=False)
    op.drop_constraint(op.f('clients_manager_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.alter_column('contractors', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_contractors_company_id'), 'contractors', ['company_id'], unique=False)
    op.drop_constraint(op.f('contractors_company_id_fkey'), 'contractors', type_='foreignkey')
    op.create_foreign_key(None, 'contractors', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('executors', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('executors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_executors_contractor_id'), 'executors', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_executors_stage_id'), 'executors', ['stage_id'], unique=False)
    op.create_index(op.f('ix_executors_user_id'), 'executors', ['user_id'], unique=False)
    op.drop_constraint(op.f('executors_stage_id_fkey'), 'executors', type_='foreignkey')
    op.drop_constraint(op.f('executors_user_id_fkey'), 'executors', type_='foreignkey')
    op.drop_constraint(op.f('executors_contractor_id_fkey'), 'executors', type_='foreignkey')
    op.create_foreign_key(None, 'executors', 'stages', ['stage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'executors', 'contractors', ['contractor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'executors', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('executors', 'email')
    op.add_column('projects', sa.Column('name', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('description', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('contract', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.drop_constraint(op.f('projects_client_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('refresh_tokens', sa.Column('jti', sa.String(), nullable=False))
    op.alter_column('refresh_tokens', 'device',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['jti'])
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'refresh_token')
    op.add_column('stages', sa.Column('name', sa.String(), nullable=True))
    op.add_column('stages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('stages', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('stages', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stages_project_id'), 'stages', ['project_id'], unique=False)
    op.drop_constraint(op.f('stages_project_id_fkey'), 'stages', type_='foreignkey')
    op.create_foreign_key(None, 'stages', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'stages', type_='foreignkey')
    op.create_foreign_key(op.f('stages_project_id_fkey'), 'stages', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_stages_project_id'), table_name='stages')
    op.drop_column('stages', 'end_date')
    op.drop_column('stages', 'start_date')
    op.drop_column('stages', 'description')
    op.drop_column('stages', 'name')
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'device',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('refresh_tokens', 'jti')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_client_id_fkey'), 'projects', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'contract')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'name')
    op.add_column('executors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'executors', type_='foreignkey')
    op.drop_constraint(None, 'executors', type_='foreignkey')
    op.drop_constraint(None, 'executors', type_='foreignkey')
    op.create_foreign_key(op.f('executors_contractor_id_fkey'), 'executors', 'contractors', ['contractor_id'], ['id'])
    op.create_foreign_key(op.f('executors_user_id_fkey'), 'executors', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('executors_stage_id_fkey'), 'executors', 'stages', ['stage_id'], ['id'])
    op.drop_index(op.f('ix_executors_user_id'), table_name='executors')
    op.drop_index(op.f('ix_executors_stage_id'), table_name='executors')
    op.drop_index(op.f('ix_executors_contractor_id'), table_name='executors')
    op.alter_column('executors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('executors', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'contractors', type_='foreignkey')
    op.create_foreign_key(op.f('contractors_company_id_fkey'), 'contractors', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_contractors_company_id'), table_name='contractors')
    op.alter_column('contractors', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_manager_id_fkey'), 'clients', 'users', ['manager_id'], ['id'])
    op.drop_index(op.f('ix_clients_manager_id'), table_name='clients')
    op.drop_column('clients', 'telephone')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'inn')
    op.drop_column('clients', 'company_name')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
