"""add_2

Revision ID: b6d664cc3ac6
Revises: 2dc9db0ff3a7
Create Date: 2026-02-18 15:56:13.429583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d664cc3ac6'
down_revision: Union[str, Sequence[str], None] = '2dc9db0ff3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('contractor_inn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'contractor_inn')
    # ### end Alembic commands ###
