"""add_5

Revision ID: b87388ee8b28
Revises: 0dd81f6ea1b8
Create Date: 2026-02-19 15:37:01.526244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b87388ee8b28'
down_revision: Union[str, Sequence[str], None] = '0dd81f6ea1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_branches',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('contract_name', sa.String(), nullable=True),
    sa.Column('contract_exp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_branches_branch_id'), 'contractor_branches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_contractor_branches_contractor_id'), 'contractor_branches', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_branches_id'), 'contractor_branches', ['id'], unique=False)
    op.alter_column('contractors', 'email',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('ix_contractors_branch_id'), table_name='contractors')
    op.drop_constraint(op.f('contractors_branch_id_fkey'), 'contractors', type_='foreignkey')
    op.drop_column('contractors', 'branch_id')
    op.drop_column('contractors', 'contract')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('contract', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('contractors_branch_id_fkey'), 'contractors', 'branches', ['branch_id'], ['id'])
    op.create_index(op.f('ix_contractors_branch_id'), 'contractors', ['branch_id'], unique=False)
    op.alter_column('contractors', 'email',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_contractor_branches_id'), table_name='contractor_branches')
    op.drop_index(op.f('ix_contractor_branches_contractor_id'), table_name='contractor_branches')
    op.drop_index(op.f('ix_contractor_branches_branch_id'), table_name='contractor_branches')
    op.drop_table('contractor_branches')
    # ### end Alembic commands ###
